### ISSUE TITLE
Week 05 - Day 3 - Thanksgiving Break Assignment

### ISSUE THREAD

**Issue by gstark** [mrected/assignments#18]
# Choose one or more of the following:
- Try the [Javascript Koans](https://github.com/suncoast-devs/koans)
- Implement Blackjack in React
- Implement Tic-Tac-Toe in React
- Implement [this homework](https://suncoast.io/handbook/curriculum/front-end/react-ii/assignments/snowman/)
- Go through the free [Javascript 30](https://javascript30.com)

# Videos to Watch
- Watch this [amazing video](https://vimeo.com/36579366)

**Comment by mrected** [comment]
https://github.com/mrected/koans

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![With LASERS](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8de0b77cb9bd24d453ed6e604c00bc8768a57d5c/BriskEnviousGraywolf.gif)
> &ldquo;With LASERS&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/13)**__
