### ISSUE TITLE
Week 06 - Day 3 - Choose your own API

### ISSUE THREAD

**Issue by gstark** [mrected/assignments#21]
In this assignment, you'll build a front end for an API of your choice

![Snowman](./assets/snowman.gif)

## Objectives

- Reinforce component architecture in React
- Reinforce reading of API documentation (some is great, and some is terrible)
- Creating and designing your own features for a web app

## Requirements

We're going to build a front end for an API of your choice. Choose one from [this list](https://github.com/toddmotto/public-apis)

*NOTE* You'll need to choose one with `Auth` being `No` or `apiKey` since we haven't covered `OAuth` authentication yet.

*NOTE* You'll also need to check to see if the API will work from your browser. You can do a quick check by making a small `create-react-app`, doing an `axios.get` or `fetch` of one API URL and see if you get browser errors.

### Explorer Mode

- [ ] Read your API docs
- [ ] Use Postman to make some API requests to be familiar with the API and the data it returns
- [ ] Create a list of the features you are going to create and how they will work
- [ ] Design your User Interface
- [ ] create-react-app
- [ ] Design your HTML statically in `App.js`
- [ ] Make it dynamic
- [ ] Use components when needed
- [ ] Deploy it and share it with friends

**Comment by mrected** [comment]
https://github.com/mrected/hgthmv

**Comment by mrected** [comment]
satisfying-boat.surge.sh

**Comment by gstark** [comment]
I'm not sure that surge link is correct. I get a different site.

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![Shake it cus you made it!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f8192466340c451ea46a1b17477b92f5f01a8ba7/danding%20pup.gif)
> &ldquo;Shake it cus you made it!&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/19)**__

**Comment by mrected** [comment]
It wasn't. It gave me that as a link then wouldn't let me post to it. This one works...
next-oil.surge.sh
