### ISSUE TITLE
Week 02 - Day 2 - Roshambo

### ISSUE THREAD

**Issue by gstark** [mrected/assignments#7]
Create a simple Rock-Paper-Scissors game.

## Objectives

- Work with JavaScript and the DOM
- Practice conditional logic

## Requirements

Do not worry about CSS for explorer mode, only do as HTML to show the functionality.

### Background

See the wikipedia page about [Rock, Paper, Scissors](https://en.wikipedia.org/wiki/Rock%E2%80%93paper%E2%80%93scissors)

### How to get started

- Get familiar with rock, paper, scissors if you haven't played before (or in a while)
- Draw out on paper/whiteboard/computer the rough design of your application
  - See _Explorer Mode_ for the UI requirements
- Start by placing all the HTML elements on the page
- Style the user interface
- Write out in English, ALL the steps the application needs to take
  - For example "When user one clicks on Rock, remember that user one chooses Rock"
- Start adding JavaScript to make your program to do the steps you described above

### Explorer Mode

- [ ] As a user I should be able to see three buttons for each player.
- [ ] As a user, I should be able to pick an option for each player.
- [ ] As a user, after each player makes their selection, I should be told who won and the game should be over.

### Adventure Mode

- [ ] Create a `vs computer` mode, that picks a selection.
- [ ] Modify your `vs computer` mode to follow a specific strategy (your choice)
- [ ] Make your computer AI unbeatable
- [ ] Give the user a choice to player against the various computer levels or another player
- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable

### Epic Mode

- [ ] Your game is currently only 1 vs 1, add the ability to add more computer or users players to the game

**Comment by mrected** [comment]
finished explorer and part of adventure
https://github.com/mrected/roshambo

roshambo-chris.surge.sh

**Comment by gstark** [comment]
So this line `if (havePlayersChosen[0] === true && havePlayersChosen[1] === true) {` could just be `if (havePlayersChosen[0] && havePlayersChosen[1]) {`

also consider making `havePlayersChosen` an object instead of an array. That way you can access the elements by name

```js
  let havePlayersChosen = { one: false, two: false }
```

and later on:

```js
if (havePlayersChosen.one && havePlayersChosen.two) {
```

Same with `playerChoices` -- in this case an object will be more expressive than an array.

Come see me and we can discuss some more interesting ways to tackle the `rpsLogic` method, the ternary is a nice trick, but there are some other _slick_ ways of trying to reduce the amount of logic in that function.

Also instead of using the `alt` property to store *data* (e.g. the choice the player is clicking on) lets talk about `HTML5 data properties` and how they can be used. Come see me about that as well.

All said, very nicely done. Feel free to come find me during any lab time and we can discuss the items above

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![With LASERS](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8de0b77cb9bd24d453ed6e604c00bc8768a57d5c/BriskEnviousGraywolf.gif)
> &ldquo;With LASERS&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/13)**__
